version: "3"

services:

  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/geoserverconfig:/opt/geoserver_data
      - ./geoserver/tomcatconfig:/opt/apache-tomcat-9.0.75/conf
